name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 17.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: ionic build

      - name: Copy Android
        run: ionic capacitor copy android        
              
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      #- name: Build Android Dev APK
      #  run: ionic capacitor build android

      #- name: Build Android Release APK
      #  run: ionic capacitor build android --release --prod

      - name: Generate the Android App Bundle
        working-directory: ./android/
        run: ./gradlew bundle

      - name: Generate the Android App Bundle Release
        working-directory: ./android/
        run: ./gradlew bundleRelease

      - name: Generate the Debug Apk
        working-directory: ./android/
        run: ./gradlew assembleDebug
        
      - name: Generate the release Apk
        working-directory: ./android/
        run: ./gradlew assembleRelease
  
      - name: List files 
        run: |
          pwd
          ls -R ${{ github.workspace }}/android/app/build/outputs
          
      - name: Save release bundle as artifact
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
        with:
          name: app-release
          path: |
            ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
            ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk

